DEVELOP-5826 bills cache
Storyous/android-libraries pull request #112
Opened 2022-05-04 11:22 UTC by ibartj

2022-05-04 15:59 UTC, Vaek requested changes

2022-05-04 15:59 UTC, Vaek commented on bills/src/main/java/com/storyous/bills/api/model.kt
> +    val code: String?,
Neměl by bejt spíš celej field OrderProvider nullable?

2022-05-04 15:59 UTC, Vaek commented on bills/src/main/java/com/storyous/bills/db/Converters.kt
> +    fun jsonToBillItems(value: String?): List<CachedBillItem>? {
Na co celá tahle magie?

2022-05-04 16:03 UTC, Vaek requested changes

2022-05-04 16:03 UTC, Vaek commented on bills/src/main/java/com/storyous/bills/db/model.kt
> +    val orderProvider: OrderProvider,
dal bych nullable

2022-05-04 16:03 UTC, Vaek commented on bills/src/main/java/com/storyous/bills/db/model.kt
> +    val invoiceData: InvoiceData,
nullable

2022-05-04 16:03 UTC, Vaek commented on bills/src/main/java/com/storyous/bills/db/model.kt
> +    val desk: Desk,                     // ** deskId -> desk
nullable

2022-05-04 16:03 UTC, Vaek commented on bills/src/main/java/com/storyous/bills/db/model.kt
> +    val paymentBillId: Int,
neměl by bejt taky nullable?

2022-05-05 08:22 UTC, ibartj commented on bills/src/main/java/com/storyous/bills/db/model.kt
> +    val orderProvider: OrderProvider,
✅

2022-05-05 08:22 UTC, ibartj commented on bills/src/main/java/com/storyous/bills/db/model.kt
> +    val invoiceData: InvoiceData,
✅

2022-05-05 08:22 UTC, ibartj commented on bills/src/main/java/com/storyous/bills/db/model.kt
> +    val desk: Desk,                     // ** deskId -> desk
✅

2022-05-05 08:22 UTC, ibartj commented on bills/src/main/java/com/storyous/bills/db/model.kt
> +    val paymentBillId: Int,
✅

2022-05-05 08:22 UTC, ibartj commented on bills/src/main/java/com/storyous/bills/db/Converters.kt
> +    fun jsonToBillItems(value: String?): List<CachedBillItem>? {
✅

2022-05-05 08:22 UTC, ibartj commented on bills/src/main/java/com/storyous/bills/db/BillsDatabase.kt
> +        var gson = GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ssZ").create()
✅

2022-05-05 08:22 UTC, ibartj commented on bills/src/main/java/com/storyous/bills/api/model.kt
> +    val code: String?,
✅

2022-05-05 08:22 UTC, ibartj commented on bills/src/main/java/com/storyous/bills/api/model.kt
> +    val items: List<BillItem>,
✅

2022-05-05 09:31 UTC, Vaek approved these changes

2022-05-05 11:26 UTC, merged