DEVELOP-4501 delivery activity to fragment refactor
Storyous/android-libraries pull request #72
Opened 2021-03-22 14:02 UTC by ibartj

2021-03-22 15:50 UTC, Vaek requested changes

2021-03-22 15:50 UTC, Vaek commented on delivery/src/main/java/com/storyous/delivery/common/DeliveryActivity.kt
> -        DeliveryConfiguration.onActivityToolbarCreate(toolbar, supportFragmentManager)
Tohle se nemělo mazat, bude chybět logout tlačítko

2021-03-22 18:32 UTC, ibartj commented on delivery/src/main/java/com/storyous/delivery/common/DeliveryActivity.kt
> -        DeliveryConfiguration.onActivityToolbarCreate(toolbar, supportFragmentManager)
OK, já se těšil, že se toho zbavíme.

2021-03-23 10:14 UTC, Vaek approved these changes

2021-03-23 10:14 UTC, merged