DEVELOP-4958 kronos library instead of truetime
Storyous/android-libraries pull request #85
Opened 2021-08-18 13:18 UTC by ibartj

2021-08-20 06:57 UTC, aronluka requested changes

2021-08-20 07:13 UTC, ibartj commented on common_utils/src/main/java/com/storyous/commonutils/TimestampUtilKronos.java
> +    // third party library can throw any exception possible
✔️

2021-08-22 08:37 UTC, aronluka requested changes

2021-08-22 08:37 UTC, aronluka commented on common_utils/src/main/java/com/storyous/commonutils/TimestampUtil.java
> +   // third party library can throw any exception possible
ještě tady odstranit, jsem předtím přehllédl.

2021-08-22 08:37 UTC, aronluka commented on common_utils/src/main/java/com/storyous/commonutils/TimestampUtilTruetime.java
> +                    format(new Date())
Co ještě rovnou otagovat všechny logování truetime, ať je v tom pořádek kdy se co volalo

2021-08-23 09:10 UTC, ibartj commented on common_utils/src/main/java/com/storyous/commonutils/TimestampUtil.java
> +   // third party library can throw any exception possible
✔️

2021-08-23 09:10 UTC, ibartj commented on common_utils/src/main/java/com/storyous/commonutils/TimestampUtilTruetime.java
> +                    format(new Date())
✔️

2021-08-23 09:14 UTC, aronluka approved these changes

2021-08-23 09:14 UTC, merged